//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ_myself.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoint
    {
        public int id { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string building { get; set; }
    }
}
