//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ_myself.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrders
    {
        public int id { get; set; }
        public System.DateTime createtime { get; set; }
        public System.DateTime deliverytime { get; set; }
        public int idpickup { get; set; }
        public int iduser { get; set; }
        public string code { get; set; }
        public int idstatuszakaza { get; set; }
    }
}
