//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ_myself.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Articule { get; set; }
        public int idnametovar { get; set; }
        public int idedizm { get; set; }
        public decimal price { get; set; }
        public int idpostavshik { get; set; }
        public int idproizvoditel { get; set; }
        public int idcategorytovar { get; set; }
        public decimal discount { get; set; }
        public decimal amountstock { get; set; }
        public string description { get; set; }
        public string images { get; set; }


        public string ColorAt
        {
            get
            {
                if (discount > 15)
                {
                    return @"#008080";
                }
                else if (amountstock == 0)
                {
                    return @"#ff0090ff";
                }
                else
                {
                    return @"#ffffffff";
                }
            }
        }

        public string OldPrice
        {
            get
            {
                if (discount == 0)
                {
                    return null;
                }
                else return price.ToString() + "  ";
            }
        }

        public string GetPrice
        {
            get
            {
                if (discount == 0)
                    return price.ToString();
                else 
                    return (price * (100 - discount) / 100).ToString() + "  ";
            }
        }
    }
}
