//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ_myself.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int iduser { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronmic { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int idrole { get; set; }
    }
}
